# Generated by Django 5.1.7 on 2025-08-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('gambar', models.ImageField(upload_to='gallery/')),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JamLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari1', models.CharField(max_length=50)),
                ('hari2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KepalaDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='kepala_desa/')),
                ('sambutan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telepon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='LayananCepat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LokasiKantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VisiMisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visi', models.TextField()),
                ('misi', models.TextField(help_text='Isi dengan list misi, pisahkan baris dengan enter')),
            ],
        ),
        migrations.RemoveField(
            model_name='berita',
            name='gambar',
        ),
        migrations.AlterField(
            model_name='berita',
            name='judul',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='berita',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
