# Generated by Django 5.1.7 on 2025-08-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desaapp', '0002_galeri_jamlayanan_kepaladesa_kontak_layanancepat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('file_type', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Pengumuman', 'Pengumuman'), ('Kegiatan', 'Kegiatan'), ('Pembangunan', 'Pembangunan'), ('UMKM', 'UMKM'), ('Kesehatan', 'Kesehatan')], max_length=50)),
                ('image', models.URLField(blank=True, null=True)),
                ('is_important', models.BooleanField(default=False)),
            ],
        ),
    ]
