# Generated by Django 5.1.7 on 2025-08-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desaapp', '0003_document_event_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telepon', models.CharField(blank=True, max_length=20)),
                ('bagian', models.CharField(blank=True, max_length=50)),
                ('subjek', models.CharField(max_length=200)),
                ('pesan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
