# Generated by Django 5.1.7 on 2025-08-29 01:12

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desaapp', '0005_delete_berita_news_slug_alter_news_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='pesan',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Pesan'),
        ),
        migrations.AlterField(
            model_name='galeri',
            name='deskripsi',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Deskripsi Galeri'),
        ),
        migrations.AlterField(
            model_name='kepaladesa',
            name='sambutan',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sambutan Kepala Desa'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Isi Berita'),
        ),
        migrations.AlterField(
            model_name='news',
            name='excerpt',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Ringkasan Berita'),
        ),
        migrations.AlterField(
            model_name='visimisi',
            name='misi',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Isi dengan list misi, pisahkan baris dengan enter', verbose_name='Misi Desa'),
        ),
        migrations.AlterField(
            model_name='visimisi',
            name='visi',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Visi Desa'),
        ),
    ]
