# Generated by Django 5.1.7 on 2025-09-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desaapp', '0006_alter_contactmessage_pesan_alter_galeri_deskripsi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source_url',
            field=models.URLField(blank=True, help_text='Link ke website sumber berita', null=True),
        ),
    ]
