# Generated by Django 5.1.7 on 2025-09-07 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desaapp', '0007_news_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Kegiatan Warga', 'Kegiatan Warga'), ('Pembangunan', 'Pembangunan'), ('UMKM', 'UMKM'), ('Budaya', 'Budaya'), ('Alam', 'Alam')], max_length=50)),
                ('type', models.CharField(choices=[('photo', 'Foto'), ('video', 'Video')], default='photo', max_length=10)),
                ('thumbnail', models.ImageField(upload_to='gallery/thumbnails/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/images/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='desaapp.gallery')),
            ],
        ),
        migrations.DeleteModel(
            name='Galeri',
        ),
        migrations.AlterField(
            model_name='news',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
