# Generated by Django 5.1.7 on 2025-09-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desaapp', '0008_gallery_galleryimage_delete_galeri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='gallery/videos/'),
        ),
    ]
