# Generated by Django 5.1.7 on 2025-09-08 16:05

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desaapp', '0009_gallery_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SejarahDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='Sejarah Desa Sidomulyo', max_length=200)),
                ('isi', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Isi Sejarah Desa')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sejarah Desa',
                'verbose_name_plural': 'Sejarah Desa',
            },
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='type',
        ),
    ]
