# Generated by Django 5.1.7 on 2025-09-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desaapp', '0010_sejarahdesa_remove_gallery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visimisi',
            name='judul',
            field=models.CharField(default='Visi & Misi Desa', max_length=200),
        ),
    ]
