# Generated by Django 5.1.7 on 2025-09-21 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desaapp', '0011_visimisi_judul'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('processing_time', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=100)),
                ('requirements', models.TextField(blank=True, help_text='Pisahkan dengan enter')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('nik', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Diproses'), ('in_progress', 'Sedang Diproses'), ('done', 'Selesai'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desaapp.service')),
            ],
        ),
    ]
