# Generated by Django 5.1.7 on 2025-09-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desaapp', '0012_service_servicerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='address',
            new_name='alamat',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='submitted_at',
            new_name='tanggal',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='status',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='nama',
            field=models.CharField(default='Anonim', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Kependudukan', 'Kependudukan'), ('Sosial', 'Sosial'), ('Perizinan', 'Perizinan'), ('Ekonomi', 'Ekonomi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='fee',
            field=models.CharField(default='Gratis', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='requirements',
            field=models.TextField(help_text='Pisahkan dengan koma (,)'),
        ),
    ]
