# Generated by Django 5.1.7 on 2025-09-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desaapp', '0013_rename_address_servicerequest_alamat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu'), ('in_progress', 'Diproses'), ('done', 'Selesai'), ('rejected', 'Ditolak')], default='pending', max_length=20),
        ),
    ]
