# Generated by Django 5.1.7 on 2025-11-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desaapp', '0014_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('Kegiatan Warga', 'Kegiatan Warga'), ('Pembangunan', 'Pembangunan'), ('UMKM', 'UMKM'), ('Budaya', 'Budaya'), ('Alam', 'Alam'), ('Pariwisata', 'Pariwisata')], max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Pengumuman', 'Pengumuman'), ('Kegiatan', 'Kegiatan'), ('Pembangunan', 'Pembangunan'), ('UMKM', 'UMKM'), ('Kesehatan', 'Kesehatan'), ('Pariwisata', 'Pariwisata')], max_length=50),
        ),
    ]
